version: '3'
services:
  mongo-server:
    image: 'mongo'
    ports:
      - "27018:27017"
  java-app:
    restart: 'on-failure'
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongo-server:27017/mapap